version: '3.1'

services:
  mongo: 
    image : mongo:5.0.3
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: aungmyatmoe11
      MONGO_INITDB_ROOT_PASSWORD: passwordpassword

  mongo-express:
    image : mongo-express
    ports :
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: aungmyatmoe11
      ME_CONFIG_MONGODB_ADMINPASSWORD: passwordpassword
      ME_CONFIG_MONGODB_URL: mongodb+srv://aungmyatmoedev11:passwordpassword@go-ecommerce.odc9gct.mongodb.net/?retryWrites=true&w=majority&appName=go-ecommerce